### ISSUE TITLE
Use VSEARCH instead of USEARCH

### ISSUE THREAD

**Issue by StuntsPT** [dereneaton/pyrad#5]
Recently VSEARCH was released:
https://github.com/torognes/vsearch
This is an open source reimplementation of the USEARCH program.
It works _almost_ as a drop-in replacement for USEARCH, but not quite. I had to drop the "quiet" argument (does not exist yet in vsearch) so the output is now quite a bit more verbose.
The results are also supposed to be _very_ similar between both programs as can be seen in the benchmarks in VSEARCH's README, however, VSEARCH is _much_ faster.
Here are some benchmarks I have performed using your test dataset in my laptop (i7-4700QM). All settings in "params.txt" were left at default except the number of threads used.
1 thread (steps 2,3,4,5,6,7):
USEARCH - 629,36s user 25,26s system 93% cpu 11:42,47 total
VSEARCH - 377,12s user 33,32s system 93% cpu 7:16,67 total
6 threads (steps 2,3,4,5,6,7):
USEARCH - 627,21s user 42,84s system 98% cpu 11:40,46 total
VSEARCH - 598,98s user 43,67s system 448% cpu 2:23,14 total

The results files are, however, slightly different:
vcf files:
USEARCH: 

```
VCFtools - v0.1.12b
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
        --vcf analysis_usearch/outfiles/c88d6m4p3.vcf
        --maf 0.15
        --max-missing 0.5

Eighth Header entry should be INFO: INFO    
After filtering, kept 12 out of 12 Individuals
After filtering, kept 2339 out of a possible 7847 Sites
Run Time = 0.00 seconds
```

VSEARCH:

```
VCFtools - v0.1.12b
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
        --vcf analysis/outfiles/c88d6m4p3.vcf
        --maf 0.15
        --max-missing 0.5

Eighth Header entry should be INFO: INFO    
After filtering, kept 12 out of 12 Individuals
After filtering, kept 2039 out of a possible 6685 Sites
Run Time = 0.00 seconds

```

This could, however, be due to some differences in default search parameters in both programs. I didn't look into it yet.
I have modified pyRAD in my own branch to allow it to use both USEARCH and VSEARCH.
Next up is my pull request.

Let me know what you think of it.

**Comment by torognes** [comment]
@dereneaton FYI vsearch 1.1.1 now supports the --quiet option.
